### ISSUE TITLE
Ajouter validation CNIL dans les attributs de l'enrollment

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier-courtier-back#16]
Dans le formulaire du front, il y a une case à cocher "Je déclare avoir accompli mes démarches CNIL en accord avec le règlement général de protection des données"
Or, cela ne se retrouve pas côté enrollement.

**Comment by Flightan** [comment]
@pknoth c'est déjà fait ?

**Comment by annemarie35** [comment]
Je me demande si c'est iso.
- on a `t.boolean "demarche_cnil"`
Dans la PR #81 côté back https://github.com/betagouv/api-particulier-courtier-back/blob/US-front%2381-entrants-techniques/db/schema.rb
- dans le front on a 
```js
    <div className='form__group'>
            <input type='checkbox' name='enrollment.checkbox-cnil' id='checkbox-cnil'/>
            <label htmlFor='checkbox-cnil' className='label-inline'>Je déclare avoir accompli mes démarches CNIL en accord avec le règlement général de protection des données</label>
          </div>
``` en V2
